baseURL = 'http://lotusotho.com/posts/new-blogroll.md'
languageCode = 'en-us'
title = 'Lotusotho Little Website'
theme = 'm10c'

[params]

author = "Lotusotho"
description = "My little blogroll"
avatar = "./img/capybara.jpg"
# [[menu.main]]
   # identifier = "newblog"
   # name = "New Blog"
   # url = "/content/newblog/"

[menu]
   [[menu.main]]
   identifier = "home"
   name = "Home"
   url = "/posts/new-blogroll.md"
   weight = 1

   [[menu.main]]
   identifier = "about"
   name = "About"
   url = "/about/"
   weight = 1

[[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/lotusotho"