baseURL = 'http://lotusotho.com/'
languageCode = 'en-us'
title = 'Lotusotho Place'
theme = "m10c"
author = "Lotusotho"
description = "My little blogroll"

[[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/lotusotho"